[[pages]]
path = "app.py"
name = "Home"
icon = ":material/home:"

[[pages]]
path = "app_pages/1_Overview.py"
name = "Overview"
icon = ":material/analytics:"

[[pages]]
path = "app_pages/2_RFM_Segmentation.py"
name = "RFM Segmentation"
icon = ":material/hub:"

[[pages]]
path = "app_pages/3_Churn_Prediction.py"
name = "Churn Prediction"
icon = ":material/trending_down:"

[[pages]]
path = "app_pages/4_CLV_Prediction.py"
name = "CLV Prediction"
icon = ":material/payments:"

[[pages]]
path = "app_pages/5_Revenue_Forecasting.py"
name = "Revenue Forecasting"
icon = ":material/show_chart:"
