[[pages]]
path = "app.py"
name = "Home"
icon = "🏠"

[[pages]]
path = "pages/1_Overview.py"
name = "Overview"
icon = "📈"

[[pages]]
path = "pages/2_RFM_Segmentation.py"
name = "RFM Segmentation"
icon = "🧩"

[[pages]]
path = "pages/3_Churn_Prediction.py"
name = "Churn Prediction"
icon = "🔄"

[[pages]]
path = "pages/4_CLV_Prediction.py"
name = "CLV Prediction"
icon = "💰"

[[pages]]
path = "pages/5_Revenue_Forecasting.py"
name = "Revenue Forecasting"
icon = "🔮"
